CREATE PROCEDURE PRACTICE.TOP_RESOURCE_USAGE
@TOPPERSCENT TINYINT = 10
AS
BEGIN

IF @TOPPERSCENT > 50 
BEGIN
	RAISERROR('якхьйнл анкэьни опнжемр', 16, 1)
	RETURN
END

DECLARE @SQL VARCHAR(MAX)

SELECT @SQL = '
SELECT TOP '+CAST(@TOPPERSCENT AS VARCHAR(2))+' LOGIN_NAME
FROM
(
SELECT L.LOGIN_NAME, SUM(I.LOGICAL_READS) AS SUM_LOGICAL_READS
FROM PRACTICE.INFORMATION I
	INNER JOIN PRACTICE.DIC_LOGINS L ON L.ID = I.LOGIN_ID
GROUP BY L.LOGIN_NAME
) TAB 
ORDER BY SUM_LOGICAL_READS DESC'

EXEC (@SQL)

END
