CREATE TRIGGER PRACTICE.INSERT_EXCEPTION
ON PRACTICE.EXCEPTION
INSTEAD OF INSERT
AS
BEGIN
	IF NOT EXISTS
		(
		SELECT * FROM INSERTED
		WHERE 1=1
		AND ((EXCEPTION_TYPE = 'TIME' AND (TIME_FROM IS NULL OR TIME_TO IS NULL OR DATE_TO IS NOT NULL OR DATE_FROM IS NOT NULL))
		OR (EXCEPTION_TYPE = 'DATE' AND (TIME_FROM IS NOT NULL OR TIME_TO IS NOT NULL OR DATE_TO IS NULL OR DATE_FROM IS NULL))
		OR (EXCEPTION_TYPE = 'EXCLUSIVE' AND (TIME_FROM IS NOT NULL OR TIME_TO IS NOT NULL OR DATE_TO IS NOT NULL OR DATE_FROM IS NOT NULL)))
		)
	BEGIN
		INSERT INTO PRACTICE.EXCEPTION (LOGIN_ID,TIME_FROM,TIME_TO,DATE_FROM,DATE_TO,EXCEPTION_TYPE,ZHURNAL_ID,PRIORITY1)
		OUTPUT INSERTED.ID,INSERTED.LOGIN_ID,INSERTED.TIME_FROM,INSERTED.TIME_TO,INSERTED.DATE_FROM,INSERTED.DATE_TO,INSERTED.EXCEPTION_TYPE,GETDATE(),'днаюбкемхе' 
		INTO PRACTICE.EXCEPTION_LOG (EXCEPTION_ID, LOGIN_ID,TIME_FROM,TIME_TO,DATE_FROM,DATE_TO,EXCEPTION_TYPE,DATE_CHANGE,ACTION1)
		SELECT LOGIN_ID,TIME_FROM,TIME_TO,DATE_FROM,DATE_TO,EXCEPTION_TYPE,ZHURNAL_ID,PRIORITY1  FROM INSERTED
	END
	ELSE 
		RAISERROR ('ньхайю! мебепмши ббнд дюммшу', 16,1)
END;
