CREATE PROCEDURE PRACTICE.DELETED_SESSIONS_RESOURCES_ON_ONE_SESSION
@ZHURNAL_ID INT
AS
	IF OBJECT_ID('TEMPDB..#REZULT') IS NOT NULL
		DROP TABLE #REZULT
	SELECT TAB.LOGIN_ID,TAB.CPU,TAB.LOGICAL_READS,TAB.RAM_USAGE,B.CPU AS SETTINGS_CPU,B.LOGICAL_READS AS SETTINGS_LOGICAL_READS,B.RAM AS SETTINGS_RAM,
	CASE
		WHEN TAB.CPU > B.CPU THEN 'CPU'
		WHEN TAB.LOGICAL_READS > B.LOGICAL_READS THEN 'LOGICAL_READS'
		WHEN TAB.RAM_USAGE > B.RAM THEN 'RAM'
	END CAUSE
	INTO #REZULT
	FROM
	(
		SELECT A.LOGIN_ID, A.CPU_USAGE AS CPU,A.LOGICAL_READS AS LOGICAL_READS,A.RAM_USAGE AS RAM_USAGE 
		FROM PRACTICE.INFORMATION A
		WHERE A.ZHURNAL_ID = @ZHURNAL_ID AND A.LOGIN_ID NOT IN (SELECT D.LOGIN_ID FROM PRACTICE.EXCEPTION D WHERE A.ZHURNAL_ID = D.ZHURNAL_ID)
	) TAB
	INNER JOIN PRACTICE.SETINGS B ON TAB.CPU > B.CPU OR TAB.LOGICAL_READS > B.LOGICAL_READS OR TAB.RAM_USAGE > B.RAM

	INSERT INTO PRACTICE.DELETED_SESSIONS(BLOCK_SESSION, BLOCK_LOGIN_ID,ZHURNAL_ID,ACTION1)
	SELECT A.SESSION_ID, A.LOGIN_ID, A.ZHURNAL_ID,'анкэьне онрпеакемхе CPU' FROM #REZULT B
	JOIN PRACTICE.INFORMATION A 
	ON A.CPU_USAGE = B.CPU AND A.LOGIN_ID = B.LOGIN_ID AND A.LOGICAL_READS = B.LOGICAL_READS AND A.RAM_USAGE = B.RAM_USAGE WHERE B.CAUSE = 'CPU' 
		
	INSERT INTO PRACTICE.DELETED_SESSIONS(BLOCK_SESSION, BLOCK_LOGIN_ID,ZHURNAL_ID,ACTION1)
	SELECT A.SESSION_ID, A.LOGIN_ID, A.ZHURNAL_ID,'анкэьне онрпеакемхе LOGICAL_READS' FROM #REZULT B
	JOIN PRACTICE.INFORMATION A 
	ON A.CPU_USAGE = B.CPU AND A.LOGIN_ID = B.LOGIN_ID AND A.LOGICAL_READS = B.LOGICAL_READS AND A.RAM_USAGE = B.RAM_USAGE WHERE B.CAUSE = 'LOGICAL_READS'

	INSERT INTO PRACTICE.DELETED_SESSIONS(BLOCK_SESSION, BLOCK_LOGIN_ID,ZHURNAL_ID,ACTION1)
	SELECT A.SESSION_ID, A.LOGIN_ID, A.ZHURNAL_ID,'анкэьне онрпеакемхе RAM' FROM #REZULT B
	JOIN PRACTICE.INFORMATION A 
	ON A.CPU_USAGE = B.CPU AND A.LOGIN_ID = B.LOGIN_ID AND A.LOGICAL_READS = B.LOGICAL_READS AND A.RAM_USAGE = B.RAM_USAGE WHERE B.CAUSE = 'RAM'
