CREATE PROCEDURE PRACTICE.DELETE_SESSION3
@ZHURNAL_ID INT
AS
BEGIN
	IF OBJECT_ID('TEMPDB..#REZULT') IS NOT NULL
		DROP TABLE #REZULT

	SELECT A.BLOCKING_SESSION_ID AS BLOCK_SESSION,B.LOGIN_ID AS BLOCK_LOGIN_ID, D.EXCEPTION_TYPE AS EXCEPTION_TYPE1,D.PRIORITY1 AS PRIORITY1, A.SESSION_ID AS SESSION_ID,
	T.LOGIN_ID AS LOGIN2, R.EXCEPTION_TYPE AS EXCEPTION_TYPE2, R.PRIORITY1 AS PRIORITY2,E.ID AS ZHURNAL_ID
	INTO #REZULT
	FROM PRACTICE.BLOCKING A
	JOIN PRACTICE.INFORMATION B ON A.BLOCKING_SESSION_ID = B.SESSION_ID
	LEFT JOIN PRACTICE.EXCEPTION D ON D.LOGIN_ID = B.LOGIN_ID AND CASE 
																		WHEN D.EXCEPTION_TYPE = 'EXCLUSIVE' THEN 1 
																		WHEN D.EXCEPTION_TYPE = 'DATE' AND GETDATE() BETWEEN D.DATE_FROM AND D.DATE_TO THEN 1
																		WHEN D.EXCEPTION_TYPE = 'TIME' AND CONVERT (TIME, CURRENT_TIMESTAMP) BETWEEN D.TIME_FROM AND D.TIME_TO THEN 1
																  END = 1
	JOIN PRACTICE.ZHURNAL E ON E.ID = A.ZHURNAL_ID AND B.ZHURNAL_ID = E.ID
	JOIN PRACTICE.INFORMATION T ON T.SESSION_ID = A.SESSION_ID AND T.ZHURNAL_ID = E.ID
	LEFT JOIN PRACTICE.EXCEPTION R ON R.LOGIN_ID = T.LOGIN_ID AND CASE
																		WHEN R.EXCEPTION_TYPE = 'EXCLUSIVE' THEN 1 
																		WHEN R.EXCEPTION_TYPE = 'DATE' AND GETDATE() BETWEEN R.DATE_FROM AND R.DATE_TO THEN 1
																		WHEN R.EXCEPTION_TYPE = 'TIME' AND CONVERT (TIME, CURRENT_TIMESTAMP) BETWEEN R.TIME_FROM AND R.TIME_TO THEN 1 
																  END = 1
	WHERE (R.EXCEPTION_TYPE IS NOT NULL AND D.EXCEPTION_TYPE IS NOT NULL) AND E.ID = @ZHURNAL_ID AND D.PRIORITY1 > R.PRIORITY1 
	
	DELETE B
	FROM PRACTICE.DELETED_SESSIONS B JOIN #REZULT A ON A.BLOCK_SESSION = B.BLOCK_SESSION AND A.SESSION_ID = B.SESSION_ID AND A.EXCEPTION_TYPE1 = B.EXCEPTION_TYPE1
	WHERE B.ZHURNAL_ID = @ZHURNAL_ID

	INSERT INTO PRACTICE.DELETED_SESSIONS( BLOCK_SESSION , BLOCK_LOGIN_ID,  EXCEPTION_TYPE1,PRIORITY1, SESSION_ID ,LOGIN2, EXCEPTION_TYPE2,PRIORITY2,ZHURNAL_ID,ACTION1)
	SELECT T.BLOCK_SESSION, T.BLOCK_LOGIN_ID,  T.EXCEPTION_TYPE1,T.PRIORITY1, T.SESSION_ID ,T.LOGIN2, T.EXCEPTION_TYPE2,T.PRIORITY2,T.ZHURNAL_ID,'USER ¡ÀŒ »–”≈“ USER`A ¬¿∆Õ≈≈ —≈¡ﬂ' FROM #REZULT T
END
